Name: "Buildpacks"

on:
  push:
    branches: main
jobs:
  publish:
    name: Publish
    runs-on:
      - ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: setup-tools
        uses: buildpacks/github-actions/setup-tools@v5.5.4
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v5.5.4
      - id: package
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          
          BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
          VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
          PACKAGE="${REPO}/$(echo "$BP_ID" | sed 's/\//_/g')"
          
          pack buildpack package --publish ${PACKAGE}:${VERSION} --tag  ${PACKAGE}:latest
        shell: bash
        env:
          REPO: ghcr.io/${{ github.repository }}
