name: "Buildpacks"

on:
  push:
    branches: main
jobs:
  publish:
    name: Publish
    runs-on:
      - ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: setup-tools
        uses: buildpacks/github-actions/setup-tools@v5.5.4
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v5.5.4
      - id: package
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          
          cd migration-process 
          
          BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
          VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
          PACKAGE="${REPO}/$(echo "$BP_ID" | sed 's/\//_/g')"
          IMAGE_NAME=${PACKAGE}:${VERSION}
          
          pack buildpack package --publish ${IMAGE_NAME}
          echo "bp_image_name=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"
          echo "bp_package=${PACKAGE}" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          REPO: ghcr.io/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Tag as latest
        run: |
          docker buildx imagetools create ${{ steps.package.outputs.bp_image_name }} --tag ${{  steps.package.outputs.bp_package }}:latest
